name: Android-ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://fabernovel/android:api-31-v1.6.0
    steps:
      - uses: actions/checkout@v4
      - name: Build with Gradle
        run: ./gradlew dependencies
      - name: Test
        run: ./gradlew test
