name: Android-ci

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

env:
  ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
  API_KEY: ${{ secrets.API_KEY }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - my_android_job:
          runs-on: ubuntu-22.04 # Works also with self hosted runner supporting docker
          container:
            image: docker://fabernovel/android:api-29-v1.1.0
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew dependencies
      - name: Test
        run: ./gradlew test