name: Publishing to Sonatype
on:
  release:
    types: [published]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Install Android SDK packages
        run: sdkmanager "platform-tools" "platforms;android-36" "build-tools;36.0.0"
      - name: Prepare gradle.properties
        run: |
          cd sift
          echo -e "${{ secrets.SECRING }}" | base64 -d > ./secring.gpg   
          echo "signing.keyId=${{ secrets.KEYID }}" >> ./gradle.properties
          echo "signing.password=${{ secrets.PASS }}" >> ./gradle.properties
          echo "signing.secretKeyRingFile=$(pwd)/secring.gpg" >> ./gradle.properties
          echo "NEXUS_USERNAME=${{ secrets.SUSER }}" >> ./gradle.properties
          echo "NEXUS_PASSWORD=${{ secrets.SPASSWORD }}" >> ./gradle.properties
      - name: Sonatype Publish
        run: |
          ./gradlew :sift:publishReleasePublicationToSonatypeRepository
          BEARER=$(printf "${{ secrets.SUSER }}:${{ secrets.SPASSWORD }}" | base64)
          curl --request POST \
            --verbose \
            --header "Authorization: Bearer ${BEARER}" \
            https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/${{ secrets.SREPO_ID }}
